#!/bin/bash

# Get the current working directory
current_dir=$(pwd)

# Print the absolute path of the current working directory
echo "The absolute path of the current working directory is: $current_dir"
